/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembrosIndexRouteImport } from './routes/membros/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as MembrosCarteirinhaValidarRouteImport } from './routes/membros/carteirinha/validar'
import { Route as MembrosCarteirinhaNovaRouteImport } from './routes/membros/carteirinha/nova'
import { Route as MembrosCarteirinhaIdRouteImport } from './routes/membros/carteirinha/$id'

const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosIndexRoute = MembrosIndexRouteImport.update({
  id: '/membros/',
  path: '/membros/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosCarteirinhaValidarRoute =
  MembrosCarteirinhaValidarRouteImport.update({
    id: '/membros/carteirinha/validar',
    path: '/membros/carteirinha/validar',
    getParentRoute: () => rootRouteImport,
  } as any)
const MembrosCarteirinhaNovaRoute = MembrosCarteirinhaNovaRouteImport.update({
  id: '/membros/carteirinha/nova',
  path: '/membros/carteirinha/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosCarteirinhaIdRoute = MembrosCarteirinhaIdRouteImport.update({
  id: '/membros/carteirinha/$id',
  path: '/membros/carteirinha/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/triagem': typeof TriagemRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/membros/': typeof MembrosIndexRoute
  '/membros/carteirinha/$id': typeof MembrosCarteirinhaIdRoute
  '/membros/carteirinha/nova': typeof MembrosCarteirinhaNovaRoute
  '/membros/carteirinha/validar': typeof MembrosCarteirinhaValidarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/triagem': typeof TriagemRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/membros': typeof MembrosIndexRoute
  '/membros/carteirinha/$id': typeof MembrosCarteirinhaIdRoute
  '/membros/carteirinha/nova': typeof MembrosCarteirinhaNovaRoute
  '/membros/carteirinha/validar': typeof MembrosCarteirinhaValidarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/triagem': typeof TriagemRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/membros/': typeof MembrosIndexRoute
  '/membros/carteirinha/$id': typeof MembrosCarteirinhaIdRoute
  '/membros/carteirinha/nova': typeof MembrosCarteirinhaNovaRoute
  '/membros/carteirinha/validar': typeof MembrosCarteirinhaValidarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/politica-de-privacidade'
    | '/triagem'
    | '/blog/$slug'
    | '/blog/'
    | '/membros/'
    | '/membros/carteirinha/$id'
    | '/membros/carteirinha/nova'
    | '/membros/carteirinha/validar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/politica-de-privacidade'
    | '/triagem'
    | '/blog/$slug'
    | '/blog'
    | '/membros'
    | '/membros/carteirinha/$id'
    | '/membros/carteirinha/nova'
    | '/membros/carteirinha/validar'
  id:
    | '__root__'
    | '/'
    | '/politica-de-privacidade'
    | '/triagem'
    | '/blog/$slug'
    | '/blog/'
    | '/membros/'
    | '/membros/carteirinha/$id'
    | '/membros/carteirinha/nova'
    | '/membros/carteirinha/validar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TriagemRoute: typeof TriagemRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MembrosIndexRoute: typeof MembrosIndexRoute
  MembrosCarteirinhaIdRoute: typeof MembrosCarteirinhaIdRoute
  MembrosCarteirinhaNovaRoute: typeof MembrosCarteirinhaNovaRoute
  MembrosCarteirinhaValidarRoute: typeof MembrosCarteirinhaValidarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/': {
      id: '/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof MembrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/carteirinha/validar': {
      id: '/membros/carteirinha/validar'
      path: '/membros/carteirinha/validar'
      fullPath: '/membros/carteirinha/validar'
      preLoaderRoute: typeof MembrosCarteirinhaValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/carteirinha/nova': {
      id: '/membros/carteirinha/nova'
      path: '/membros/carteirinha/nova'
      fullPath: '/membros/carteirinha/nova'
      preLoaderRoute: typeof MembrosCarteirinhaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/carteirinha/$id': {
      id: '/membros/carteirinha/$id'
      path: '/membros/carteirinha/$id'
      fullPath: '/membros/carteirinha/$id'
      preLoaderRoute: typeof MembrosCarteirinhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TriagemRoute: TriagemRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  MembrosIndexRoute: MembrosIndexRoute,
  MembrosCarteirinhaIdRoute: MembrosCarteirinhaIdRoute,
  MembrosCarteirinhaNovaRoute: MembrosCarteirinhaNovaRoute,
  MembrosCarteirinhaValidarRoute: MembrosCarteirinhaValidarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
