/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriagemRouteImport } from './routes/triagem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembrosIndexRouteImport } from './routes/membros/index'
import { Route as MembrosCarteirinhaValidarRouteImport } from './routes/membros/carteirinha/validar'
import { Route as MembrosCarteirinhaNovaRouteImport } from './routes/membros/carteirinha/nova'
import { Route as MembrosCarteirinhaIdRouteImport } from './routes/membros/carteirinha/$id'

const TriagemRoute = TriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosIndexRoute = MembrosIndexRouteImport.update({
  id: '/membros/',
  path: '/membros/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosCarteirinhaValidarRoute =
  MembrosCarteirinhaValidarRouteImport.update({
    id: '/membros/carteirinha/validar',
    path: '/membros/carteirinha/validar',
    getParentRoute: () => rootRouteImport,
  } as any)
const MembrosCarteirinhaNovaRoute = MembrosCarteirinhaNovaRouteImport.update({
  id: '/membros/carteirinha/nova',
  path: '/membros/carteirinha/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosCarteirinhaIdRoute = MembrosCarteirinhaIdRouteImport.update({
  id: '/membros/carteirinha/$id',
  path: '/membros/carteirinha/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/triagem': typeof TriagemRoute
  '/membros/': typeof MembrosIndexRoute
  '/membros/carteirinha/$id': typeof MembrosCarteirinhaIdRoute
  '/membros/carteirinha/nova': typeof MembrosCarteirinhaNovaRoute
  '/membros/carteirinha/validar': typeof MembrosCarteirinhaValidarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/triagem': typeof TriagemRoute
  '/membros': typeof MembrosIndexRoute
  '/membros/carteirinha/$id': typeof MembrosCarteirinhaIdRoute
  '/membros/carteirinha/nova': typeof MembrosCarteirinhaNovaRoute
  '/membros/carteirinha/validar': typeof MembrosCarteirinhaValidarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/triagem': typeof TriagemRoute
  '/membros/': typeof MembrosIndexRoute
  '/membros/carteirinha/$id': typeof MembrosCarteirinhaIdRoute
  '/membros/carteirinha/nova': typeof MembrosCarteirinhaNovaRoute
  '/membros/carteirinha/validar': typeof MembrosCarteirinhaValidarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/triagem'
    | '/membros/'
    | '/membros/carteirinha/$id'
    | '/membros/carteirinha/nova'
    | '/membros/carteirinha/validar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/triagem'
    | '/membros'
    | '/membros/carteirinha/$id'
    | '/membros/carteirinha/nova'
    | '/membros/carteirinha/validar'
  id:
    | '__root__'
    | '/'
    | '/triagem'
    | '/membros/'
    | '/membros/carteirinha/$id'
    | '/membros/carteirinha/nova'
    | '/membros/carteirinha/validar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TriagemRoute: typeof TriagemRoute
  MembrosIndexRoute: typeof MembrosIndexRoute
  MembrosCarteirinhaIdRoute: typeof MembrosCarteirinhaIdRoute
  MembrosCarteirinhaNovaRoute: typeof MembrosCarteirinhaNovaRoute
  MembrosCarteirinhaValidarRoute: typeof MembrosCarteirinhaValidarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triagem': {
      id: '/triagem'
      path: '/triagem'
      fullPath: '/triagem'
      preLoaderRoute: typeof TriagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/': {
      id: '/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof MembrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/carteirinha/validar': {
      id: '/membros/carteirinha/validar'
      path: '/membros/carteirinha/validar'
      fullPath: '/membros/carteirinha/validar'
      preLoaderRoute: typeof MembrosCarteirinhaValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/carteirinha/nova': {
      id: '/membros/carteirinha/nova'
      path: '/membros/carteirinha/nova'
      fullPath: '/membros/carteirinha/nova'
      preLoaderRoute: typeof MembrosCarteirinhaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros/carteirinha/$id': {
      id: '/membros/carteirinha/$id'
      path: '/membros/carteirinha/$id'
      fullPath: '/membros/carteirinha/$id'
      preLoaderRoute: typeof MembrosCarteirinhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TriagemRoute: TriagemRoute,
  MembrosIndexRoute: MembrosIndexRoute,
  MembrosCarteirinhaIdRoute: MembrosCarteirinhaIdRoute,
  MembrosCarteirinhaNovaRoute: MembrosCarteirinhaNovaRoute,
  MembrosCarteirinhaValidarRoute: MembrosCarteirinhaValidarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
